title: Site

tabs:
  # Pages Tab
  pages:
    label:
      en: Pages
    icon: page
    sections:
      pages:
        headline: Pages
        type: pages
        layout: cards
        size: tiny
        status: listed
        image: false
      seo:
        type: fields
        fields:
          line:
            type: line
          seoDescription:
            label: SEO Description
            help: Text appearing on search engines
            type: textarea
            buttons: false
            width: 1/2
          seoImage:
            type: files
            label: SEO Image
            max: 1
            width: 1/2
