title: Site

tabs:
  # Pages Tab
  pages:
    label:
      en: Pages
    icon: page
    sections:
      pages:
        headline: Pages
        type: pages
        status: published
        # layout: cards
        image: false
      invisible:
        headline: Invisible
        type: pages
        status: drafts

  # Footer Tab
  footer:
    label: Footer
    icon: angle-down
    fields:
      copyright:
        label: Copyright
        type: textarea
      facebook:
        label: Facebook Account
        type: text
        icon: facebook
        before: https://facebook.com/
        width: 1/2
      instagram:
        label: Instagram Account
        type: text
        icon: instagram
        before: https://instagram.com/
        width: 1/2

  # Seo Tab
  seo:
    label: SEO
    icon: search
    columns:
      - width: 2/3
        sections:
          seoContent:
            type: fields
            fields:
              metaDescription:
                label: SEO Description
                help: Write help text
                type: textarea
                buttons: false

      - width: 1/3
        sections:
          seoImages:
            type: files
            headline: SEO Image
            min: 1
            max: 1
